# Generated by Django 3.2 on 2024-11-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Буду смотреть', 'Буду смотреть'), ('Смотрю', 'Смотрю'), ('Просмотрено', 'Просмотрено')], max_length=20)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.animeshnik')),
            ],
            options={
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
