# Generated by Django 3.2 on 2024-11-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_useranimestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, to='anime.Genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.URLField(blank=True, default='default_anime.png', null=True),
        ),
    ]
