# Generated by Django 3.2 on 2024-11-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_auto_20241106_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(blank=True, default='default_anime.png', null=True, upload_to=''),
        ),
    ]
