# Generated by Django 3.2 on 2024-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_anime_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.URLField(blank=True, default='default_anime.png', null=True),
        ),
    ]
