# Generated by Django 3.2 on 2024-11-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_anime_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('image', models.URLField(blank=True, default='default_anime.png', null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(choices=[('deleted', 'Deleted'), ('modified', 'Modified')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
                ('genres', models.ManyToManyField(blank=True, to='anime.Genre')),
            ],
        ),
    ]
