# Generated by Django 3.2 on 2024-11-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_animehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animehistory',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='animehistory',
            name='change_type',
            field=models.CharField(choices=[('modified', 'modified'), ('deleted', 'deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animehistory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
