# Generated by Django 3.2 on 2024-11-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_auto_20241111_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animehistory',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime'),
        ),
        migrations.AlterField(
            model_name='animehistory',
            name='change_type',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('modified', 'Modified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animehistory',
            name='image',
            field=models.URLField(blank=True, default='default_anime.png', null=True),
        ),
    ]
