# Generated by Django 3.2 on 2024-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20241111_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeshnik',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], max_length=15, null=True),
        ),
    ]
